version: '3.8'

services:
  db:
    image: mariadb:10.6
    container_name: ca_db
    restart: always
    ports:
      - "3306:3306" 
    environment:
      MYSQL_ROOT_PASSWORD: root_password_seguro
      MYSQL_DATABASE: collectiveaccess
      MYSQL_USER: ca_user
      MYSQL_PASSWORD: ca_password_segura
    volumes:
      - ca_db_data:/var/lib/mysql

  providence:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: ca_backend
    restart: always
    ports:
      - "3510:80"
    volumes:
      # FICAR RUTA DEL DIRECTORI QUE REBRA LES IMATGES PREPARADES
      #- "C:\\Users\\user\\Desktop\\CA_IMAGENES_BACKEND:/var/www/html/media"
      
      # FICAR RUTA DEL DIRECTORI ON ESTARAN LES FOTOS NORMALS
      # - "C:\\Users\\user\\Desktop\\CA_IMPORT_MEDIOS:/var/www/html/import"
    depends_on:
      - db

volumes:
  ca_db_data: